- name: docker create
  hosts: localhost
  tasks:

    - docker_container:
        name: jupyter-{{ user.name }}
        state: started
        image: "{{ container_image }}"
        # command: sleep 10m
        auto_remove: true
        detach: true
        # debug: true
        env: "{{ spawner_environment }}"
        published_ports:
          - "8888"
      register: container_info

    - debug: var=container_info
    # "set_fact: ansiblespawner_out" will be passed back to the spawner
    # Must contain fields "ip" and "port"
    - set_fact:
        ansiblespawner_out:
          container: "{{ container_info.container }}"
          ip: 127.0.0.1
          port: "{{ container_info.ansible_facts.docker_container.NetworkSettings.Ports['8888/tcp'].0.HostPort }}"
