---
# https://molecule.readthedocs.io/en/latest/configuration.html
dependency:
  name: galaxy
  options:
    role-file: ${ANSIBLESPAWNER_ANSIBLE_PATH}requirements.yml
    requirements-file: ${ANSIBLESPAWNER_ANSIBLE_PATH}requirements.yml
driver:
  name: podman
platforms:
  # https://www.reddit.com/r/ansible/comments/klxcn0/how_to_use_a_customer_dockerfilej2_with_molecule/
  - name: jupyterhub
    image: docker.io/library/amazonlinux:2
    dockerfile: ../resources/Dockerfile.j2
    pre_build_image: false
    command: /sbin/init
    tmpfs:
      /run: rw
      /tmp: rw
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  log: True
  inventory:
    host_vars:
      jupyterhub:
        ansible_python_interpreter: /usr/bin/python3
        jupyter_ec2_key_name: test-key
        jupyter_ec2_subnet: test-subnet
        ssh_private_key: ${MOLECULE_PROJECT_DIRECTORY}/ci/dummy-id_rsa.pem}
  playbooks:
    converge: ${ANSIBLESPAWNER_ANSIBLE_PATH-../../}jupyterhub-deploy.yml
# scenario:
#   converge_sequence:
#     - converge
verifier:
  name: ansible
scenario:
  converge_sequence:
    - converge
