repos:
  - repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
      - id: black
        args: [--target-version=py36]
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [
            # default black line length is 88
            --max-line-length=88,
            # F821 undefined name 'c'
            "--per-file-ignores=**/jupyterhub_config.py:F821",
          ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        files: ^ansiblespawner
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.2
    hooks:
      - id: prettier
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.2
    hooks:
      - id: yamllint
        args: [--config-data=relaxed]
