repos:
- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
  - id: black
    args: [--target-version=py36]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.1
  hooks:
  - id: flake8
    args: [
      # default black line length is 88
      --max-line-length=88,
      # F821 undefined name 'c'
      "--per-file-ignores=**/jupyterhub_config.py:F821",
    ]
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.23.0
  hooks:
  - id: yamllint
    args: [--config-data=relaxed]
