---
# ansible-galaxy collection install -p collections -r requirements.yml

# The AWS modules are split into two collections:
# https://www.ansible.com/blog/getting-started-with-aws-ansible-module-development

collections:
  # https://galaxy.ansible.com/ui/repo/published/community/general/
  - name: community.general
    version: 10.3.0
  # https://galaxy.ansible.com/ui/repo/published/amazon/aws/
  - name: amazon.aws
    version: 9.1.1

# ansible-galaxy role install -p roles -r requirements.yml
roles:
  # https://github.com/evandam/evandam.conda
  - name: evandam.conda
    version: v1.2.0
