{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

ENV container=docker

RUN dnf makecache && dnf --assumeyes install /usr/bin/python3 /usr/bin/python3-config /usr/bin/dnf-3 sudo bash iproute

# Install systemd so that we can overwrite it without other packages overwriting our change
RUN dnf -y install systemd
RUN curl -sfLo /usr/bin/systemctl https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/v1.5.8066/files/docker/systemctl3.py && \
    chmod a+x /usr/bin/systemctl && \
    ln -sf /usr/bin/systemctl /sbin/init

VOLUME ["/sys/fs/cgroup"]
CMD ["/sbin/init"]
