---
# https://molecule.readthedocs.io/en/latest/configuration.html
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: localhost
provisioner:
  name: ansible
  log: True
  ansible_args:
    - -e jupyterhub_deploy=false -e ssh_public_key=ci/dummy-id_rsa.pub
  env:
    AWS_ACCESS_KEY_ID: test
    AWS_SECRET_ACCESS_KEY: test
    AWS_REGION: eu-west-1
    EC2_URL: http://localhost:4566
  inventory:
    host_vars:
      localhost:
        ansible_python_interpreter: "${VIRTUAL_ENV:-$CONDA_PREFIX}/bin/python3"
        jupyterhub_deploy: False
  playbooks:
    converge: ../../jupyterhub-provision.yml
scenario:
  test_sequence:
    # Due to limitations with localstack we can only run the playbook once
    - lint
    - dependency
    - syntax
    - converge
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
