{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}


ENV container=docker

# RUN yum -y install systemd ; \
#     cd /lib/systemd/system/sysinit.target.wants/ ; \
#     for i in *; do [ $i = systemd-tmpfiles-setup.service ] || rm -f $i ; done ; \
#     rm -f /lib/systemd/system/multi-user.target.wants/* ; \
#     rm -f /etc/systemd/system/*.wants/* ; \
#     rm -f /lib/systemd/system/local-fs.target.wants/* ; \
#     rm -f /lib/systemd/system/sockets.target.wants/*udev* ; \
#     rm -f /lib/systemd/system/sockets.target.wants/*initctl* ; \
#     rm -f /lib/systemd/system/basic.target.wants/* ; \
#     rm -f /lib/systemd/system/anaconda.target.wants/*

# Install systemd so that we can overwrite it without other packages overwriting our change
RUN yum -y install python3 sudo systemd
RUN curl -sfLo /usr/bin/systemctl https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/9cbe1a00eb4bdac6ff05b96ca34ec9ed3d8fc06c/files/docker/systemctl3.py && \
    chmod a+x /usr/bin/systemctl && \
    ln -sf /usr/bin/systemctl /sbin/init

VOLUME ["/sys/fs/cgroup"]
CMD ["/sbin/init"]
