# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

name: Build
on: [push, pull_request]

jobs:

  # https://github.com/pre-commit/action
  pre-commit:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0

  test:
    name: Test
    strategy:
      # fail-fast: false
      matrix:
        pytestmark:
          - not docker
          - not podman
    runs-on: ubuntu-20.04
    steps:
      - name: Enable rootless podman
        run: |
          sudo apt-get update -q
          sudo apt-get install -q -y fuse-overlayfs
          podman info
          slirp4netns --version
          fuse-overlayfs --version
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions/setup-node@v1
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install -r dev-requirements.txt
          npm install -g configurable-http-proxy
      - run: env | sort
      - name: Update setuptools_scm version
        run: python setup.py build
      - name: Install Ansible requirements
        run: |
          cd examples/podman
          ansible-galaxy collection install -p collections -r requirements.yml
          cd ../..
      - name: Run tests
        run: pytest --cov=ansiblespawner tests -vs -m "${{ matrix.pytestmark }}" --cov-report=xml --cov-report=term-missing --cov-fail-under=95
        # https://github.com/marketplace/actions/codecov
      - name: Upload coverage stats
        uses: codecov/codecov-action@v1
        # https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
        # Upload regardless of whether tests pass or fail
        if: ${{ !cancelled() }}
        with:
          file: ./coverage.xml
          # fail_ci_if_error: true
